/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface ChatApp {
    }
    interface ChatMessage {
        "msg": any;
    }
    interface ChatScreen {
        "isBlankChat": boolean;
        "thread": any;
    }
    interface ChatSidebar {
        "active": string;
        "threads": any[];
    }
    interface SpendidResults {
    }
}
export interface ChatMessageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatMessageElement;
}
export interface ChatScreenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatScreenElement;
}
export interface ChatSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatSidebarElement;
}
export interface SpendidResultsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpendidResultsElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLChatAppElement extends Components.ChatApp, HTMLStencilElement {
    }
    var HTMLChatAppElement: {
        prototype: HTMLChatAppElement;
        new (): HTMLChatAppElement;
    };
    interface HTMLChatMessageElementEventMap {
        "handleOption": string;
    }
    interface HTMLChatMessageElement extends Components.ChatMessage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatMessageElementEventMap>(type: K, listener: (this: HTMLChatMessageElement, ev: ChatMessageCustomEvent<HTMLChatMessageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatMessageElementEventMap>(type: K, listener: (this: HTMLChatMessageElement, ev: ChatMessageCustomEvent<HTMLChatMessageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatMessageElement: {
        prototype: HTMLChatMessageElement;
        new (): HTMLChatMessageElement;
    };
    interface HTMLChatScreenElementEventMap {
        "sendMessage": { text: string; ts: number };
        "showResult": boolean;
    }
    interface HTMLChatScreenElement extends Components.ChatScreen, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatScreenElementEventMap>(type: K, listener: (this: HTMLChatScreenElement, ev: ChatScreenCustomEvent<HTMLChatScreenElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatScreenElementEventMap>(type: K, listener: (this: HTMLChatScreenElement, ev: ChatScreenCustomEvent<HTMLChatScreenElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatScreenElement: {
        prototype: HTMLChatScreenElement;
        new (): HTMLChatScreenElement;
    };
    interface HTMLChatSidebarElementEventMap {
        "newThread": void;
    }
    interface HTMLChatSidebarElement extends Components.ChatSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatSidebarElementEventMap>(type: K, listener: (this: HTMLChatSidebarElement, ev: ChatSidebarCustomEvent<HTMLChatSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatSidebarElementEventMap>(type: K, listener: (this: HTMLChatSidebarElement, ev: ChatSidebarCustomEvent<HTMLChatSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatSidebarElement: {
        prototype: HTMLChatSidebarElement;
        new (): HTMLChatSidebarElement;
    };
    interface HTMLSpendidResultsElementEventMap {
        "closeResult": boolean;
    }
    interface HTMLSpendidResultsElement extends Components.SpendidResults, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpendidResultsElementEventMap>(type: K, listener: (this: HTMLSpendidResultsElement, ev: SpendidResultsCustomEvent<HTMLSpendidResultsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpendidResultsElementEventMap>(type: K, listener: (this: HTMLSpendidResultsElement, ev: SpendidResultsCustomEvent<HTMLSpendidResultsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpendidResultsElement: {
        prototype: HTMLSpendidResultsElement;
        new (): HTMLSpendidResultsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "chat-app": HTMLChatAppElement;
        "chat-message": HTMLChatMessageElement;
        "chat-screen": HTMLChatScreenElement;
        "chat-sidebar": HTMLChatSidebarElement;
        "spendid-results": HTMLSpendidResultsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface ChatApp {
    }
    interface ChatMessage {
        "msg"?: any;
        "onHandleOption"?: (event: ChatMessageCustomEvent<string>) => void;
    }
    interface ChatScreen {
        "isBlankChat"?: boolean;
        "onSendMessage"?: (event: ChatScreenCustomEvent<{ text: string; ts: number }>) => void;
        "onShowResult"?: (event: ChatScreenCustomEvent<boolean>) => void;
        "thread"?: any;
    }
    interface ChatSidebar {
        "active"?: string;
        "onNewThread"?: (event: ChatSidebarCustomEvent<void>) => void;
        "threads"?: any[];
    }
    interface SpendidResults {
        "onCloseResult"?: (event: SpendidResultsCustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "chat-app": ChatApp;
        "chat-message": ChatMessage;
        "chat-screen": ChatScreen;
        "chat-sidebar": ChatSidebar;
        "spendid-results": SpendidResults;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "chat-app": LocalJSX.ChatApp & JSXBase.HTMLAttributes<HTMLChatAppElement>;
            "chat-message": LocalJSX.ChatMessage & JSXBase.HTMLAttributes<HTMLChatMessageElement>;
            "chat-screen": LocalJSX.ChatScreen & JSXBase.HTMLAttributes<HTMLChatScreenElement>;
            "chat-sidebar": LocalJSX.ChatSidebar & JSXBase.HTMLAttributes<HTMLChatSidebarElement>;
            "spendid-results": LocalJSX.SpendidResults & JSXBase.HTMLAttributes<HTMLSpendidResultsElement>;
        }
    }
}
