/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface BudgetScoreCard {
        "grade": string;
        "peerScore": number;
        "score": number;
    }
    interface ChatApp {
    }
    interface ChatScreen {
        "activeThread": string;
        "isBlankChat": boolean;
        "thread": any;
    }
    interface ChatSidebar {
        "active": string;
        "threads": any[];
    }
    interface CircularProgress {
        "size": number;
        "strokeWidth": number;
        "value": number;
    }
    interface MonthlySavings {
        "data": { label: string; value: number; color: string }[];
    }
    interface PieChart {
        /**
          * dark/light mode
         */
        "dark": boolean;
        /**
          * Array of items like: { category: string; monthly: number; dol?: number }
         */
        "data": any[];
        /**
          * "$" or "%"
         */
        "type": string;
    }
    interface SavingAbilityCard {
        "amount": string;
        "label": string;
        "tag": string;
    }
    interface SpeedometerGauge {
        "value": number;
    }
    interface SpendidGauge {
        "max": number;
        "value": number;
    }
    interface SpendidResults {
        "thread": any;
    }
}
export interface ChatScreenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatScreenElement;
}
export interface ChatSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatSidebarElement;
}
export interface SpendidResultsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpendidResultsElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBudgetScoreCardElement extends Components.BudgetScoreCard, HTMLStencilElement {
    }
    var HTMLBudgetScoreCardElement: {
        prototype: HTMLBudgetScoreCardElement;
        new (): HTMLBudgetScoreCardElement;
    };
    interface HTMLChatAppElement extends Components.ChatApp, HTMLStencilElement {
    }
    var HTMLChatAppElement: {
        prototype: HTMLChatAppElement;
        new (): HTMLChatAppElement;
    };
    interface HTMLChatScreenElementEventMap {
        "sendMessage": { text: string; ts: number; messages: ChatMessage[] };
        "showResult": boolean;
    }
    interface HTMLChatScreenElement extends Components.ChatScreen, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatScreenElementEventMap>(type: K, listener: (this: HTMLChatScreenElement, ev: ChatScreenCustomEvent<HTMLChatScreenElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatScreenElementEventMap>(type: K, listener: (this: HTMLChatScreenElement, ev: ChatScreenCustomEvent<HTMLChatScreenElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatScreenElement: {
        prototype: HTMLChatScreenElement;
        new (): HTMLChatScreenElement;
    };
    interface HTMLChatSidebarElementEventMap {
        "newThread": void;
        "closeResult": boolean;
    }
    interface HTMLChatSidebarElement extends Components.ChatSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatSidebarElementEventMap>(type: K, listener: (this: HTMLChatSidebarElement, ev: ChatSidebarCustomEvent<HTMLChatSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatSidebarElementEventMap>(type: K, listener: (this: HTMLChatSidebarElement, ev: ChatSidebarCustomEvent<HTMLChatSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatSidebarElement: {
        prototype: HTMLChatSidebarElement;
        new (): HTMLChatSidebarElement;
    };
    interface HTMLCircularProgressElement extends Components.CircularProgress, HTMLStencilElement {
    }
    var HTMLCircularProgressElement: {
        prototype: HTMLCircularProgressElement;
        new (): HTMLCircularProgressElement;
    };
    interface HTMLMonthlySavingsElement extends Components.MonthlySavings, HTMLStencilElement {
    }
    var HTMLMonthlySavingsElement: {
        prototype: HTMLMonthlySavingsElement;
        new (): HTMLMonthlySavingsElement;
    };
    interface HTMLPieChartElement extends Components.PieChart, HTMLStencilElement {
    }
    var HTMLPieChartElement: {
        prototype: HTMLPieChartElement;
        new (): HTMLPieChartElement;
    };
    interface HTMLSavingAbilityCardElement extends Components.SavingAbilityCard, HTMLStencilElement {
    }
    var HTMLSavingAbilityCardElement: {
        prototype: HTMLSavingAbilityCardElement;
        new (): HTMLSavingAbilityCardElement;
    };
    interface HTMLSpeedometerGaugeElement extends Components.SpeedometerGauge, HTMLStencilElement {
    }
    var HTMLSpeedometerGaugeElement: {
        prototype: HTMLSpeedometerGaugeElement;
        new (): HTMLSpeedometerGaugeElement;
    };
    interface HTMLSpendidGaugeElement extends Components.SpendidGauge, HTMLStencilElement {
    }
    var HTMLSpendidGaugeElement: {
        prototype: HTMLSpendidGaugeElement;
        new (): HTMLSpendidGaugeElement;
    };
    interface HTMLSpendidResultsElementEventMap {
        "closeResult": boolean;
    }
    interface HTMLSpendidResultsElement extends Components.SpendidResults, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpendidResultsElementEventMap>(type: K, listener: (this: HTMLSpendidResultsElement, ev: SpendidResultsCustomEvent<HTMLSpendidResultsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpendidResultsElementEventMap>(type: K, listener: (this: HTMLSpendidResultsElement, ev: SpendidResultsCustomEvent<HTMLSpendidResultsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpendidResultsElement: {
        prototype: HTMLSpendidResultsElement;
        new (): HTMLSpendidResultsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "budget-score-card": HTMLBudgetScoreCardElement;
        "chat-app": HTMLChatAppElement;
        "chat-screen": HTMLChatScreenElement;
        "chat-sidebar": HTMLChatSidebarElement;
        "circular-progress": HTMLCircularProgressElement;
        "monthly-savings": HTMLMonthlySavingsElement;
        "pie-chart": HTMLPieChartElement;
        "saving-ability-card": HTMLSavingAbilityCardElement;
        "speedometer-gauge": HTMLSpeedometerGaugeElement;
        "spendid-gauge": HTMLSpendidGaugeElement;
        "spendid-results": HTMLSpendidResultsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface BudgetScoreCard {
        "grade"?: string;
        "peerScore"?: number;
        "score"?: number;
    }
    interface ChatApp {
    }
    interface ChatScreen {
        "activeThread"?: string;
        "isBlankChat"?: boolean;
        "onSendMessage"?: (event: ChatScreenCustomEvent<{ text: string; ts: number; messages: ChatMessage[] }>) => void;
        "onShowResult"?: (event: ChatScreenCustomEvent<boolean>) => void;
        "thread"?: any;
    }
    interface ChatSidebar {
        "active"?: string;
        "onCloseResult"?: (event: ChatSidebarCustomEvent<boolean>) => void;
        "onNewThread"?: (event: ChatSidebarCustomEvent<void>) => void;
        "threads"?: any[];
    }
    interface CircularProgress {
        "size"?: number;
        "strokeWidth"?: number;
        "value"?: number;
    }
    interface MonthlySavings {
        "data"?: { label: string; value: number; color: string }[];
    }
    interface PieChart {
        /**
          * dark/light mode
         */
        "dark"?: boolean;
        /**
          * Array of items like: { category: string; monthly: number; dol?: number }
         */
        "data"?: any[];
        /**
          * "$" or "%"
         */
        "type"?: string;
    }
    interface SavingAbilityCard {
        "amount"?: string;
        "label"?: string;
        "tag"?: string;
    }
    interface SpeedometerGauge {
        "value"?: number;
    }
    interface SpendidGauge {
        "max"?: number;
        "value"?: number;
    }
    interface SpendidResults {
        "onCloseResult"?: (event: SpendidResultsCustomEvent<boolean>) => void;
        "thread"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "budget-score-card": BudgetScoreCard;
        "chat-app": ChatApp;
        "chat-screen": ChatScreen;
        "chat-sidebar": ChatSidebar;
        "circular-progress": CircularProgress;
        "monthly-savings": MonthlySavings;
        "pie-chart": PieChart;
        "saving-ability-card": SavingAbilityCard;
        "speedometer-gauge": SpeedometerGauge;
        "spendid-gauge": SpendidGauge;
        "spendid-results": SpendidResults;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "budget-score-card": LocalJSX.BudgetScoreCard & JSXBase.HTMLAttributes<HTMLBudgetScoreCardElement>;
            "chat-app": LocalJSX.ChatApp & JSXBase.HTMLAttributes<HTMLChatAppElement>;
            "chat-screen": LocalJSX.ChatScreen & JSXBase.HTMLAttributes<HTMLChatScreenElement>;
            "chat-sidebar": LocalJSX.ChatSidebar & JSXBase.HTMLAttributes<HTMLChatSidebarElement>;
            "circular-progress": LocalJSX.CircularProgress & JSXBase.HTMLAttributes<HTMLCircularProgressElement>;
            "monthly-savings": LocalJSX.MonthlySavings & JSXBase.HTMLAttributes<HTMLMonthlySavingsElement>;
            "pie-chart": LocalJSX.PieChart & JSXBase.HTMLAttributes<HTMLPieChartElement>;
            "saving-ability-card": LocalJSX.SavingAbilityCard & JSXBase.HTMLAttributes<HTMLSavingAbilityCardElement>;
            "speedometer-gauge": LocalJSX.SpeedometerGauge & JSXBase.HTMLAttributes<HTMLSpeedometerGaugeElement>;
            "spendid-gauge": LocalJSX.SpendidGauge & JSXBase.HTMLAttributes<HTMLSpendidGaugeElement>;
            "spendid-results": LocalJSX.SpendidResults & JSXBase.HTMLAttributes<HTMLSpendidResultsElement>;
        }
    }
}
